name: Build Windows Executable and Create Release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Tag name for the release"
        required: true
        default: "v1.0.0"
      body:
        description: "Release notes"
        required: false
      draft:
        description: "Create a draft release"
        required: false
        default: false
      prerelease:
        description: "Create a prerelease"
        required: false
        default: false
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build executable
        run: cargo build --release --target=x86_64-pc-windows-msvc

      - name: Copy files
        run: |
          mkdir ./output
          xcopy /y /f /s /i "target\x86_64-pc-windows-msvc\release\retroarch-shortcuts.exe" "./output"
          xcopy /y /f /s /i "gamedb.buf.gzip" "./output"

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r build.zip output

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.ref }}
          name: Release ${{ github.event.inputs.ref }}
          body: ${{ github.event.inputs.body }}
          draft: ${{ github.event.inputs.draft }}
          prerelease: ${{ github.event.inputs.prerelease }}
          files: |
            gamedb.buf.gzip
            ./target/x86_64-pc-windows-msvc/release/retroarch-shortcuts.exe
